name: Deploy to Cloud Run

env:
  SERVICE_NAME: portfolio

on: [push]

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: hjopel-playground

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          cd next/
          docker build -t europe-west1-docker.pkg.dev/hjopel-playground/hjopel:latest .
          docker push europe-west1-docker.pkg.dev/hjopel-playground/hjopel:latest

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy $SERVICE_NAME \
      #       --image europe-west1-docker.pkg.dev/hjopel-playground/portfolio:latest \
      #       --platform managed \
      #       --region us-central1 \
      #       --allow-unauthenticated
